export const MockMeas = { meals: [
  {
    idMeal: '52977',
    strMeal: 'Corba',
    strDrinkAlternate: null,
    strCategory: 'Side',
    strArea: 'Turkish',
    strInstructions: 'Pick through your lentils for any foreign debris,'
        + ' rinse them 2 or 3 times, drain, and set aside.  Fair warning, '
        + ' this will probably turn your lentils into a solid block that you’ll have to ',
    strTags: 'Soup',
    strYoutube: 'https://www.youtube.com/watch?v=VVnZd8A84z4',
    strIngredient1: 'Lentils',
    strIngredient2: 'Onion',
    strIngredient3: 'Carrots',
    strIngredient4: 'Tomato Puree',
    strIngredient5: 'Cumin',
    strIngredient6: 'Paprika',
    strIngredient7: 'Mint',
    strIngredient8: 'Thyme',
    strIngredient9: 'Black Pepper',
    strIngredient10: 'Red Pepper Flakes',
    strIngredient11: 'Vegetable Stock',
    strIngredient12: 'Water',
    strIngredient13: 'Sea Salt',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1 cup ',
    strMeasure2: '1 large',
    strMeasure3: '1 large',
    strMeasure4: '1 tbs',
    strMeasure5: '2 tsp',
    strMeasure6: '1 tsp ',
    strMeasure7: '1/2 tsp',
    strMeasure8: '1/2 tsp',
    strMeasure9: '1/4 tsp',
    strMeasure10: '1/4 tsp',
    strMeasure11: '4 cups ',
    strMeasure12: '1 cup ',
    strMeasure13: 'Pinch',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: 'https://findingtimeforcooking.com/main-dishes/red-lentil-soup-corba/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: '53065',
    strMeal: 'Sushi',
    strDrinkAlternate: null,
    strCategory: 'Seafood',
    strArea: 'Japanese',
    strInstructions: 'STEP 1\r\nTO MAKE SUSHI ROLLS: Pat out some rice.',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=ub68OxEypaY',
    strIngredient1: 'Sushi Rice',
    strIngredient2: 'Rice wine',
    strIngredient3: 'Caster Sugar',
    strIngredient4: 'Mayonnaise',
    strIngredient5: 'Rice wine',
    strIngredient6: 'Soy Sauce',
    strIngredient7: 'Cucumber',
    strIngredient8: '',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '300ml ',
    strMeasure2: '100ml',
    strMeasure3: '2 tbs',
    strMeasure4: '3 tbs',
    strMeasure5: '1 tbs',
    strMeasure6: '1 tbs',
    strMeasure7: '1',
    strMeasure8: ' ',
    strMeasure9: ' ',
    strMeasure10: ' ',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: 'https://www.bbcgoodfood.com/recipes/simple-sushi',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: '53060',
    strMeal: 'Burek',
    strDrinkAlternate: null,
    strCategory: 'Side',
    strArea: 'Croatian',
    strInstructions: 'Fry the finely chopped onions and minced meat in oil. ',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg',
    strTags: 'Streetfood, Onthego',
    strYoutube: 'https://www.youtube.com/watch?v=YsJXZwE5pdY',
    strIngredient1: 'Filo Pastry',
    strIngredient2: 'Minced Beef',
    strIngredient3: 'Onion',
    strIngredient4: 'Oil',
    strIngredient5: 'Salt',
    strIngredient6: 'Pepper',
    strIngredient7: '',
    strIngredient8: '',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1 Packet',
    strMeasure2: '150g',
    strMeasure3: '150g',
    strMeasure4: '40g',
    strMeasure5: 'Dash',
    strMeasure6: 'Dash',
    strMeasure7: ' ',
    strMeasure8: ' ',
    strMeasure9: ' ',
    strMeasure10: ' ',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: 'https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: '53069',
    strMeal: 'Bistek',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Filipino',
    strInstructions: '0.\tMarinate beef in soy sauce, lemon (or calamansi),',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/4pqimk1683207418.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=xOQON5_S7as',
    strIngredient1: 'Beef',
    strIngredient2: 'Soy Sauce',
    strIngredient3: 'Lemon',
    strIngredient4: 'Garlic',
    strIngredient5: 'Onion',
    strIngredient6: 'Olive Oil',
    strIngredient7: 'Water',
    strIngredient8: 'Salt',
    strMeasure1: '1 lb',
    strMeasure2: '5 tablespoons',
    strMeasure3: '1',
    strMeasure4: '3 cloves',
    strMeasure5: '3 parts ',
    strMeasure6: '4 tbs',
    strMeasure7: '1 cup ',
    strMeasure8: '1 pinch',
    strMeasure9: ' ',
    strSource: 'https://panlasangpinoy.com/bistek-tagalog-beefsteak-recipe/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: '53026',
    strMeal: 'Tamiya',
    strDrinkAlternate: null,
    strCategory: 'Vegetarian',
    strArea: 'Egyptian',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=mulqW-J3Yy4',
    strIngredient1: 'Broad Beans',
    strIngredient2: 'Spring Onions',
    strIngredient3: 'Garlic Clove',
    strIngredient4: 'Parsley',
    strIngredient5: 'Cumin',
    strIngredient6: 'Baking Powder',
    strIngredient7: 'Cayenne Pepper',
    strIngredient8: 'Flour',
    strIngredient9: 'Vegetable Oil',
    strIngredient10: '',
    strIngredient11: '',
    strMeasure1: '3 cups ',
    strMeasure2: '6',
    strMeasure3: '4',
    strMeasure4: '1/4 cup',
    strMeasure5: '2 tsp',
    strMeasure6: '1 tsp ',
    strMeasure7: '1/2 tsp',
    strMeasure8: 'Spinkling',
    strMeasure9: 'As required',
    strSource: 'https://oukosher.org/recipes/tamiya-egyptian-dried-fava-bean-fritters/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
],
};
